export const ERROR_USER_EXIST = "ERR_US_000";
export const ERROR_USER_REGISTRATION = "ERR_US_001";
export const ERROR_LOGOUT_NOT_FOUND = "ERR_LG_000";
export const ERROR_LOGOUT_UNKNOWN = "ERR_LG_999";
export const ERROR_LOGIN_CREDENTIAL = "ERR_LGN_211";
export const ERROR_UNKNOWN = "ERR-GNR-500";
